---

- name: BITBUCKET | Ensure BITBUCKET group
  group:
    name: "{{ bitbucket_group }}"
  become: yes
  become_method: sudo

- name: BITBUCKET | Ensure BITBUCKET user
  user:
    name: "{{ bitbucket_user }}"
    group: "{{ bitbucket_user }}"
    shell: /bin/bash
  become: yes
  become_method: sudo

- name: bitbucket data directory
  file:
    path: /data/bitbucket
    state: directory
    owner: "{{ bitbucket_user }}"
    mode: '0700'
  become: yes
  become_method: sudo

- name: Create a volume
  docker_volume:
    name: bitbucketVolume4
  become: yes
  become_method: sudo

- name: Create bitbucket container
  docker_container:
    name: bitbucket
    image: "atlassian/bitbucket"
    volumes:
      - /var/lib/docker/volumes/bitbucketVolume/_data:/var/atlassian/application-data/bitbucket

    ports:
      - "7990:7990"
      - "7992:7992"
      - "7993:7993"
      - "7999:7999"

    env:
      JAVA_HOME: /opt/java/openjdk
      LANG: en_US.UTF-8
      LANGUAGE: en_US:en
      LC_ALL: en_US.UTF-8
      JAVA_VERSION: jdk-11.0.16+8
      APP_NAME: bitbucket
      RUN_USER: bitbucket
      RUN_GROUP: bitbucket
      RUN_UID: "2003"
      RUN_GID: "2003"
      BITBUCKET_HOME: /var/atlassian/application-data/bitbucket
      BITBUCKET_INSTALL_DIR: /opt/atlassian/bitbucket
      SEARCH_ENABLED: "false"
      APPLICATION_MODE: default
      JRE_HOME: /opt/java/openjdk
      JAVA_BINARY: /opt/java/openjdk/bin/java
    state: started
    restart_policy: always
  become: yes
  become_method: sudo


- name: Copy bitbucket.properties to a temporary location on the control machine
  copy:
    src: roles/bitbucket/files/bitbucket.properties
    dest: /tmp/bitbucket.properties

- name: Copy bitbucket.properties file into the container
  command: docker cp /tmp/bitbucket.properties bitbucket:/var/atlassian/application-data/bitbucket/shared/bitbucket.properties
  become: yes
  become_method: sudo
